/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form_User;

import DAO.ServiceDAO;
import Main.TrangChu;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Ngọc Hùng
 */
public class FormDangNhap extends javax.swing.JFrame {

    ServiceDAO _svd;

    /**
     * Creates new form FormDangNhap
     */
    public FormDangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        _svd = new ServiceDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_DangNhap = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_DangNhap = new javax.swing.JLabel();
        txt_TenDangNhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_MatKhau = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Tên đăng nhập");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Mật khẩu");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, -1));

        btn_DangNhap.setBackground(new java.awt.Color(0, 153, 102));
        btn_DangNhap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_DangNhap.setIcon(new javax.swing.ImageIcon("E:\\Warehouse material\\Quan ly du an voi phan mem Agile\\Agile Edit\\Images\\shoe.png")); // NOI18N
        btn_DangNhap.setText("Đăng nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });
        jPanel3.add(btn_DangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 170, 50));

        btn_Thoat.setBackground(new java.awt.Color(204, 204, 204));
        btn_Thoat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_Thoat.setIcon(new javax.swing.ImageIcon("E:\\Warehouse material\\Quan ly du an voi phan mem Agile\\Agile Edit\\Images\\Thoat.png")); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 140, 50));

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel5.setText("Bạn chưa có tài khoản?");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        lbl_DangNhap.setForeground(new java.awt.Color(51, 51, 255));
        lbl_DangNhap.setText("Đăng ký ngay.");
        lbl_DangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_DangNhapMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_DangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        txt_TenDangNhap.setForeground(new java.awt.Color(204, 204, 204));
        txt_TenDangNhap.setText("Nhập tên đăng nhập");
        txt_TenDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TenDangNhapMouseClicked(evt);
            }
        });
        jPanel3.add(txt_TenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 210, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Warehouse material\\Quan ly du an voi phan mem Agile\\Agile Edit\\Images\\Logo.jpg")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 260));

        txt_MatKhau.setForeground(new java.awt.Color(204, 204, 204));
        txt_MatKhau.setText("jPasswordField1");
        txt_MatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_MatKhauMouseClicked(evt);
            }
        });
        jPanel3.add(txt_MatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 210, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 640, 260));

        jPanel2.setBackground(new java.awt.Color(211, 231, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Warehouse material\\Quan ly du an voi phan mem Agile\\Agile Edit\\Images\\LogoFormDangNhap.png")); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        // TODO add your handling code here:
        if (txt_TenDangNhap.getText().isBlank() || txt_TenDangNhap.getText().length() < 5 || txt_MatKhau.getText().isBlank() || txt_MatKhau.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "Fail");
            return;
        }
        int count = 0;
        for (User u : _svd.selectAll()) {
            if (u.getTaiKhoan().equals(txt_TenDangNhap.getText()) && u.getMatKhau().equals(txt_MatKhau.getText())) {
                count++;
            }
        }
        if (count == 0) {
            JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không tồn tại!");
        } else {
            TrangChu tc = new TrangChu();
            tc.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void lbl_DangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangNhapMouseClicked
        // TODO add your handling code here:
        FormDangKy dk = new FormDangKy();
        dk.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_DangNhapMouseClicked

    private void txt_TenDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TenDangNhapMouseClicked
        // TODO add your handling code here:
        txt_TenDangNhap.setText("");
    }//GEN-LAST:event_txt_TenDangNhapMouseClicked

    private void txt_MatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MatKhauMouseClicked
        // TODO add your handling code here:
        txt_MatKhau.setText("");
    }//GEN-LAST:event_txt_MatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_DangNhap;
    private javax.swing.JPasswordField txt_MatKhau;
    private javax.swing.JTextField txt_TenDangNhap;
    // End of variables declaration//GEN-END:variables
}
