/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form_User;

import DAO.ServiceDAO;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Ngọc Hùng
 */
public class FormDangKy extends javax.swing.JFrame {

    ServiceDAO _svd;

    /**
     * Creates new form FormDangKy
     */
    public FormDangKy() {
        initComponents();
        setLocationRelativeTo(null);
        _svd = new ServiceDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_DangKy = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_TaiKhoan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chx_DieuKhoan = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txt_MatKhau = new javax.swing.JPasswordField();
        txt_XacNhanMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(224, 238, 235));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ĐĂNG KÝ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 570, 70));

        jPanel3.setBackground(new java.awt.Color(242, 246, 248));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Tài khoản");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 154, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Mật khẩu");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 154, 30));

        btn_DangKy.setBackground(new java.awt.Color(102, 102, 255));
        btn_DangKy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_DangKy.setText("Đăng ký");
        btn_DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangKyActionPerformed(evt);
            }
        });
        jPanel3.add(btn_DangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, 40));

        btn_Thoat.setBackground(new java.awt.Color(204, 204, 204));
        btn_Thoat.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, 40));

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, -1, -1));

        txt_TaiKhoan.setForeground(new java.awt.Color(204, 204, 204));
        txt_TaiKhoan.setText("Nhập tài khoản");
        txt_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TaiKhoanMouseClicked(evt);
            }
        });
        jPanel3.add(txt_TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 227, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Xác nhận mật khẩu");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        chx_DieuKhoan.setBackground(new java.awt.Color(242, 246, 248));
        chx_DieuKhoan.setText("Tôi đồng ý với điều khoản sử dụng");
        jPanel3.add(chx_DieuKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Warehouse material\\Quan ly du an voi phan mem Agile\\Agile Edit\\Images\\user (1).png")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 210));

        txt_MatKhau.setForeground(new java.awt.Color(204, 204, 204));
        txt_MatKhau.setText("jPasswordField1");
        txt_MatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_MatKhauMouseClicked(evt);
            }
        });
        jPanel3.add(txt_MatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 230, 30));

        txt_XacNhanMatKhau.setForeground(new java.awt.Color(204, 204, 204));
        txt_XacNhanMatKhau.setText("jPasswordField1");
        txt_XacNhanMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_XacNhanMatKhauMouseClicked(evt);
            }
        });
        jPanel3.add(txt_XacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 230, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 70, 570, 291));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangKyActionPerformed
        // TODO add your handling code here:
        if (txt_TaiKhoan.getText().length() < 5 || txt_TaiKhoan.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Fail");
            return;
        }
        if (txt_MatKhau.getText().length() < 5 || txt_MatKhau.getText().isBlank()
                || txt_XacNhanMatKhau.getText().length() < 5 || txt_XacNhanMatKhau.getText().isBlank()
                || !txt_XacNhanMatKhau.getText().equals(txt_MatKhau.getText())) {
            JOptionPane.showMessageDialog(this, "Fail");
            return;
        }
        if (!chx_DieuKhoan.isSelected()) {
            JOptionPane.showMessageDialog(this, "Fail");
            return;
        }
        _svd.insert(new User(txt_TaiKhoan.getText(), txt_MatKhau.getText()));
        FormDangNhap dn = new FormDangNhap();
        dn.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_DangKyActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void txt_MatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MatKhauMouseClicked
        // TODO add your handling code here:
        txt_MatKhau.setText("");
    }//GEN-LAST:event_txt_MatKhauMouseClicked

    private void txt_XacNhanMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_XacNhanMatKhauMouseClicked
        // TODO add your handling code here:
        txt_XacNhanMatKhau.setText("");
    }//GEN-LAST:event_txt_XacNhanMatKhauMouseClicked

    private void txt_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TaiKhoanMouseClicked
        // TODO add your handling code here:
        txt_TaiKhoan.setText("");
    }//GEN-LAST:event_txt_TaiKhoanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangKy;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JCheckBox chx_DieuKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txt_MatKhau;
    private javax.swing.JTextField txt_TaiKhoan;
    private javax.swing.JPasswordField txt_XacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
