/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Connect.DBConnect;
import Model.SanPham;
import Service.SanPhamService;
import Utilites.Utilities;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ngọc Hùng
 */
public class SanPhamPanel extends javax.swing.JPanel {

    DefaultTableModel _DefaultTableModel;
    SanPhamService _spv;
    Utilites.Utilities _uUtilities = new Utilities();
    /**
     * Creates new form SanPhamPanel
     */
    public SanPhamPanel() {
        initComponents();
        _spv = new SanPhamService();
        _DefaultTableModel = new DefaultTableModel();

        loadData(_spv.getlst());
        cbx_DSP();
    }

    void cbx_DSP() {
        DefaultComboBoxModel _DefaultComboBoxModel = new DefaultComboBoxModel();
        ResultSet rs = DBConnect.getSelectDataFromDB("SELECT * FROM DONGSANPHAM");
        try {
            while (rs.next()) {
                _DefaultComboBoxModel.addElement(rs.getString(2));
            }
            cbx_MaDSP.setModel(_DefaultComboBoxModel);
        } catch (SQLException ex) {
//            Logger.getLogger(DongSanPhamService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    String getMaDSP(int id) {
        ResultSet rs = DBConnect.getSelectDataFromDB("SELECT * FROM DONGSANPHAM");
        try {
            while (rs.next()) {
                if (id == rs.getInt(1)) {
                    return rs.getString(2);
                }
            }
        } catch (SQLException ex) {
        }
        return "false";
    }

    int getIDDSP(String ma) {
        ResultSet rs = DBConnect.getSelectDataFromDB("SELECT * FROM DONGSANPHAM");
        try {
            while (rs.next()) {
                if (ma.equalsIgnoreCase(rs.getString(2))) {
                    return rs.getInt(1);
                }
            }
        } catch (SQLException ex) {
        }
        return -1;
    }

    void loadData(List<SanPham> data) {
        _DefaultTableModel = (DefaultTableModel) tbl_SanPham.getModel();
        int stt = 0;
        _DefaultTableModel.setColumnIdentifiers(new Object[]{"STT", "Mã", "Tên", "Năm bảo hành", "Trọng lượng", "Số lượng tồn", "Giá nhập", "Giá bán", "Mô tả", "Mã DSP"});
        if (data.isEmpty()) {
            _DefaultTableModel.setRowCount(0);
            return;
        }
        _DefaultTableModel.setRowCount(0);
        for (SanPham x : data) {
            _DefaultTableModel.addRow(new Object[]{++stt, x.getMa(), x.getTen(), x.getNamBaoHanh(), x.getTrongLuongSP(), x.getSLSanPhamTon(), x.getGiaNhapSP(), x.getGiaBanSP(), x.getMoTaSP(), getMaDSP(x.getIdDSP())});
        }
    }

    SanPham getDataGUI() {
//        int Id, String Ma, String Ten, int NamBaoHanh, float TrongLuongSP, String MoTaSP, int SLSanPhamTon, BigDecimal GiaNhapSP, BigDecimal GiaBanSP, int IdDSP
        return new SanPham(-1, txt_Ma.getText(), txt_Ten.getText(), Integer.parseInt(txt_NamBaoHanh.getText()), Float.parseFloat(txt_TrongLuong.getText()), txt_MoTa.getText(), Integer.parseInt(txt_SoLuongSanPhanTon.getText()), new BigDecimal(txt_GiaNhap.getText()), new BigDecimal(txt_GiaBan.getText()), getIDDSP((String) cbx_MaDSP.getSelectedItem()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_TrongLuong = new javax.swing.JTextField();
        txt_Ten = new javax.swing.JTextField();
        txt_Ma = new javax.swing.JTextField();
        txt_GiaBan = new javax.swing.JTextField();
        txt_GiaNhap = new javax.swing.JTextField();
        txt_SoLuongSanPhanTon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_MoTa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_SanPham = new javax.swing.JTable();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_SapXep = new javax.swing.JButton();
        btn_TimKiem = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        txt_TimKiem = new javax.swing.JTextField();
        rdo_ASC = new javax.swing.JRadioButton();
        rdo_DESC = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        cbx_MaDSP = new javax.swing.JComboBox<>();
        txt_NamBaoHanh = new javax.swing.JTextField();

        jLabel1.setText("Mã");

        jLabel2.setText("Mô tả");

        jLabel3.setText("Tên");

        jLabel4.setText("Năm bảo hành");

        jLabel5.setText("Số lượng tồn");

        jLabel6.setText("Trọng lượng");

        jLabel7.setText("Giá bán");

        jLabel8.setText("Giá nhập");

        txt_MoTa.setColumns(20);
        txt_MoTa.setRows(5);
        jScrollPane1.setViewportView(txt_MoTa);

        tbl_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", "Title 4"
            }
        ));
        tbl_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_SanPham);

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_SapXep.setText("Sắp xếp");
        btn_SapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SapXepActionPerformed(evt);
            }
        });

        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        rdo_ASC.setText("ASC");

        rdo_DESC.setText("DESC");

        jLabel9.setText("Mã DSP");

        cbx_MaDSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Ten)
                    .addComponent(txt_Ma)
                    .addComponent(txt_TrongLuong)
                    .addComponent(txt_SoLuongSanPhanTon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NamBaoHanh))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_GiaBan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_GiaNhap)
                    .addComponent(cbx_MaDSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_SapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_TimKiem)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdo_DESC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdo_ASC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_GiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_MaDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_NamBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_TrongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_SoLuongSanPhanTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them)
                            .addComponent(btn_TimKiem)
                            .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Sua)
                            .addComponent(btn_SapXep)
                            .addComponent(rdo_ASC))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Xoa)
                            .addComponent(rdo_DESC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        int count =0;
        if(txt_Ten.getText().isEmpty()||txt_NamBaoHanh.getText().isEmpty() ||txt_TrongLuong.getText().isEmpty()||txt_Ma.getText().isEmpty() || txt_SoLuongSanPhanTon.getText().isEmpty() || txt_GiaBan.getText().isEmpty()||txt_GiaBan.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Dữ liệu không được null và mã không được trùng");
            count++;
            return;
        }
        
        if(_uUtilities.checkSo(txt_Ten.getText()) || !_uUtilities.checkSo(txt_NamBaoHanh.getText()) || !_uUtilities.checkSo(txt_GiaBan.getText())|| !_uUtilities.checkSo(txt_GiaNhap.getText())
                || !_uUtilities.checkSo(txt_SoLuongSanPhanTon.getText()) || !_uUtilities.checkSo(txt_TrongLuong.getText())){
            JOptionPane.showMessageDialog(this, "Năm, giá, số lượng là số");
            count++;
            return;
        }
        if(count ==0){
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?", "Sửa", JOptionPane.YES_NO_OPTION);
        if (choose != 0) {
            return;
        }
        JOptionPane.showMessageDialog(this, _spv.getEditData(getDataGUI(), "UPDATE"));
        loadData(_spv.getlst());
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Săp xếp", JOptionPane.YES_NO_OPTION);
        if (choose != 0) {
            return;
        }
        JOptionPane.showMessageDialog(this, _spv.getEditData(getDataGUI(), "DELETE"));
        loadData(_spv.getlst());
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SapXepActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn sắp xếp không?", "Săp xếp", JOptionPane.YES_NO_OPTION);
        System.out.println(choose);
        if (choose != 0) {
            return;
        }
        if (rdo_ASC.isSelected()) {
            loadData(_spv.sort("DESC"));
            return;
        }
        loadData(_spv.sort("ASC"));
    }//GEN-LAST:event_btn_SapXepActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        loadData(_spv.find(txt_TimKiem.getText()));
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        int count =0;
        if(txt_Ten.getText().isEmpty()||txt_NamBaoHanh.getText().isEmpty() ||txt_TrongLuong.getText().isEmpty() || _spv.getIdexMa(txt_Ma.getText()) != -3
                ||txt_Ma.getText().isEmpty() || txt_SoLuongSanPhanTon.getText().isEmpty() || txt_GiaBan.getText().isEmpty()||txt_GiaBan.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Dữ liệu không được null và mã không được trùng");
            count++;
            return;
        }
        
        if(_uUtilities.checkSo(txt_Ten.getText()) || !_uUtilities.checkSo(txt_NamBaoHanh.getText()) || !_uUtilities.checkSo(txt_GiaBan.getText())|| !_uUtilities.checkSo(txt_GiaNhap.getText())
                || !_uUtilities.checkSo(txt_SoLuongSanPhanTon.getText()) || !_uUtilities.checkSo(txt_TrongLuong.getText())){
            JOptionPane.showMessageDialog(this, "Năm, giá, số lượng là số");
            count++;
            return;
        }
        if(count ==0){
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "Thêm", JOptionPane.YES_NO_OPTION);
        if (choose != 0) {
            return;
        }
        JOptionPane.showMessageDialog(this, _spv.getEditData(getDataGUI(), "INSERT"));
        loadData(_spv.getlst());
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void tbl_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SanPhamMouseClicked
        // TODO add your handling code here:
        int index = tbl_SanPham.getSelectedRow();
        if (index < 0) {
            return;
        }
        txt_Ma.setText(tbl_SanPham.getModel().getValueAt(index, 1).toString());
        txt_Ten.setText(tbl_SanPham.getModel().getValueAt(index, 2).toString());
        txt_NamBaoHanh.setText(tbl_SanPham.getModel().getValueAt(index, 3).toString());
        txt_TrongLuong.setText(tbl_SanPham.getModel().getValueAt(index, 4).toString());
        txt_SoLuongSanPhanTon.setText(tbl_SanPham.getModel().getValueAt(index, 5).toString());
        txt_GiaNhap.setText(tbl_SanPham.getModel().getValueAt(index, 6).toString());
        txt_GiaBan.setText(tbl_SanPham.getModel().getValueAt(index, 7).toString());
        txt_MoTa.setText(tbl_SanPham.getModel().getValueAt(index, 8).toString());
        cbx_MaDSP.setSelectedItem(tbl_SanPham.getModel().getValueAt(index, 9).toString());

    }//GEN-LAST:event_tbl_SanPhamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SapXep;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbx_MaDSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_ASC;
    private javax.swing.JRadioButton rdo_DESC;
    private javax.swing.JTable tbl_SanPham;
    private javax.swing.JTextField txt_GiaBan;
    private javax.swing.JTextField txt_GiaNhap;
    private javax.swing.JTextField txt_Ma;
    private javax.swing.JTextArea txt_MoTa;
    private javax.swing.JTextField txt_NamBaoHanh;
    private javax.swing.JTextField txt_SoLuongSanPhanTon;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_TrongLuong;
    // End of variables declaration//GEN-END:variables
}
